# La bibliothèque numpy

In [29]:
import numpy as np

Créez à partir d’une liste un array unidimensionnel et vérifiez sa taille et ce qu’il comporte.


In [30]:
arr1=np.array([2,5,7])
print(arr1.shape,arr1)

(3,) [2 5 7]


In [31]:
arr1.size

3

Générez des arrays remplis de 0 et de 1 de taille 10.


In [32]:
arr2=np.ones(10)
arr2

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [33]:
arr3=np.zeros([10,10])
arr3

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [34]:
#utilisation de arange et linspace
arr4=np.arange(1,10,dtype=int)
arr5=np.arange(1,10,0.5)
arr5

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [35]:
arr6=np.linspace(1,10,19)
arr6

array([  1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,
         5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ])

Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array


In [36]:
arr7=np.array([[1,5,9],[2,7,8]])

In [37]:
arr7**3

array([[  1, 125, 729],
       [  8, 343, 512]], dtype=int32)

Générer un array avec des valeurs entre 0 et 8, afficher les éléments 1 à 6 puis modifiez les élément 6 à 8 en leur fixant la valeur de 22.


In [38]:
arr8=np.arange(9)

In [39]:
arr8[1:7]

array([1, 2, 3, 4, 5, 6])

In [40]:
arr8[-3:]=22
arr8

array([ 0,  1,  2,  3,  4,  5, 22, 22, 22])

In [41]:
arr3[2,4]=10

Construire une matrice rectangulaire de taille 3 x 2 avec une suite de nombres commençant à 5, calculer le produit de la transposée par la matrice.


In [42]:
arr9=np.arange(5,11)
arr10=arr9.reshape(3,2)

In [43]:
arr10

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
arr9=arr9.reshape(arr10.shape)
arr9

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
np.dot(arr9.transpose(),arr9)

array([[155, 176],
       [176, 200]])

Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu


In [46]:
#on fixe la graine à 12 pour reproduire la même analyse
np.random.seed(12)
arr10=np.random.randn(100000)

In [47]:
arr10.mean()

-0.0022487200047932522

In [48]:
arr10.var()

0.99467015828060068

In [49]:
arr10=np.sort(np.where(arr10<0,0,arr10))
arr10

array([ 0.        ,  0.        ,  0.        , ...,  3.85505383,
        3.95905365,  4.07600775])

In [50]:
#passage à deux dimensions
arr11=np.random.randn(1000000).reshape(100000,10)

In [51]:
arr11.shape

(100000, 10)

In [52]:
arr11.mean(axis=0)

array([-0.00100262, -0.00313466, -0.00566402, -0.00093518, -0.00597996,
       -0.00666923, -0.00302268, -0.00154372, -0.00178218,  0.00672283])

In [53]:
np.sort(arr11,axis=0)

array([[-4.53315162, -4.11746059, -4.97281944, ..., -4.71682624,
        -4.32380957, -4.11021888],
       [-4.5168867 , -4.09938162, -4.28964506, ..., -3.98762106,
        -4.1881952 , -4.05853937],
       [-4.48131627, -4.03216405, -3.93910192, ..., -3.87921101,
        -4.04058795, -3.84216386],
       ..., 
       [ 4.03462342,  3.91860073,  4.02249442, ...,  4.16520008,
         3.83866214,  4.10567526],
       [ 4.2602162 ,  4.08405073,  4.18305185, ...,  4.26553728,
         3.87429127,  4.17656889],
       [ 4.87313701,  4.12186908,  4.67258356, ...,  4.31494347,
         4.25768748,  4.61102101]])

Générer une matrice simple et sauvegarder cette matrice dans array.npy puis dans array.txt


In [54]:
np.save("arr11",arr11)

In [55]:
np.savetxt("arr11.txt",arr11)

In [56]:
del arr11

In [57]:
arr11=np.load("arr11.npy")
arr11

array([[ 0.69710468,  1.13459656, -1.59482365, ..., -0.09068033,
        -1.98415645,  0.86822554],
       [-0.00910444,  0.81642632, -1.09784094, ...,  0.60902532,
        -0.88437205,  1.43904231],
       [ 0.18895522,  0.9377334 , -0.60005856, ..., -1.11912716,
         0.54248922, -0.19209129],
       ..., 
       [-0.49087244, -1.22883686, -0.41302535, ..., -0.64434639,
         0.06146645, -1.47652119],
       [-0.31787803,  0.93646929,  1.08378264, ...,  1.19303821,
        -0.10564258, -1.15008093],
       [-1.80520273, -0.81384461, -1.6916361 , ..., -0.85208372,
        -0.15106358, -0.02265969]])

### Gérer la mémoire et les variables chargées

In [58]:
import sys

sys.getsizeof(arr11)

8000112

In [59]:
#liste des variables
%who

arr1	 arr10	 arr11	 arr2	 arr3	 arr4	 arr5	 arr6	 arr7	 
arr8	 arr9	 np	 sys	 


In [60]:
#liste des variables avec détails
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    3: 3 elems, type `int32`, 12 bytes
arr10      ndarray    100000: 100000 elems, type `float64`, 800000 bytes (781.25 kb)
arr11      ndarray    100000x10: 1000000 elems, type `float64`, 8000000 bytes (7.62939453125 Mb)
arr2       ndarray    10: 10 elems, type `float64`, 80 bytes
arr3       ndarray    10x10: 100 elems, type `float64`, 800 bytes
arr4       ndarray    9: 9 elems, type `int32`, 36 bytes
arr5       ndarray    18: 18 elems, type `float64`, 144 bytes
arr6       ndarray    19: 19 elems, type `float64`, 152 bytes
arr7       ndarray    2x3: 6 elems, type `int32`, 24 bytes
arr8       ndarray    9: 9 elems, type `int32`, 36 bytes
arr9       ndarray    3x2: 6 elems, type `int32`, 24 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sys        module     <module 'sys' (built-in)>
